### PR TITLE
fix(swift-sdk): minimally unblock iOS CI build plumbing

### PR DESCRIPTION
**Pull request by thepastaclaw**
## Summary
Minimal CI-unblock PR for systemic iOS build failures.

This intentionally includes only build plumbing changes (no Swift API/behavior changes).

### `packages/rs-sdk-ffi/build_ios.sh`
- Added `SPV_TARGET_DIR` (workspace root target dir: `../rust-dashcore/target`)
- Fixed `BUILD_ARCH=x86` to build/use `x86_64-apple-ios` SPV sim lib
- Fixed `BUILD_ARCH=universal` to lipo SPV sim arm64 + x86_64 before simulator merge
- Standardized merged output naming to remain `librs_sdk_ffi.a` (temp + `mv`), avoiding combined-name drift

### `packages/swift-sdk/build_ios.sh`
- Replaced fragile `nm | grep` pipes with temp-file symbol checks to avoid SIGPIPE/pipefail false negatives

## Explicitly out of scope
- No changes to `packages/swift-sdk/Sources/**`
- No Swift API/deprecation/behavior adjustments
- No lockfile/tooling churn
- No app-level logic changes

## Validation
- `bash -n packages/rs-sdk-ffi/build_ios.sh`
- `bash -n packages/swift-sdk/build_ios.sh`

## Why this shape
This is a narrow CI-rescue patch so reviewers can approve quickly; follow-up refactors can be reviewed separately.

## Summary by CodeRabbit

* **Chores**
  * Improved iOS SDK build tooling for reliable device/simulator builds, toolchain-aware flows, and consistent artifact handling.
* **Refactor**
  * Consolidated library merging and packaging to produce a single consistent SDK library across build modes.
* **Bug Fixes**
  * Made symbol extraction more robust to avoid pipeline errors and handle missing optional libraries gracefully.
* **Documentation**
  * Clarified nullable provider behaviors in public API docs.

### CODE REVIEW

**Comment by thepastaclaw** [comment]
CI triage note for **Build Swift SDK and Example (no warnings)** failure:\n\n- Failing run: https://github.com/dashpay/platform/actions/runs/22265453606/job/64410693152\n- The current error (`cannot find type FFIDetailedSyncProgress / FFINetworks / FFISyncStage`) is in Swift compile after XCFramework generation.\n- This appears **pre-existing** to this branch: generating `dash_sdk_ffi.h` on `upstream/v3.1-dev` currently does not export those `FFI*` symbols either, and this workflow is broadly red on unrelated PRs as well (e.g. https://github.com/dashpay/platform/actions/runs/22264485054).\n\nSo this check failure is not a regression uniquely introduced by PR #3143; this branch mostly surfaced an already-broken Swift SDK CI path after the earlier SPV-symbol gate.

**Comment by thepastaclaw** [comment]
Addressed CodeRabbit feedback:

- ✅ **build_ios.sh partial universal SPV sim slice**: fixed in commit `096ac558a`.
  - Added an explicit warning to stderr when only one of `aarch64-apple-ios-sim` / `x86_64-apple-ios` SPV libs exists during `BUILD_ARCH=universal`.

- ℹ️ **`destroy` callback in `address_sync/provider.rs`**: this is intentionally invoked in `dash_sdk_address_provider_free(...)` (see `packages/rs-sdk-ffi/src/address_sync/mod.rs`).
  - Adding `Drop` on `CallbackAddressProvider` or `AddressProviderFFI` would risk double-destroy and also break provider reuse across multiple sync calls.

- ℹ️ **`has_pending` fallback allocation**: current fallback (`!pending_addresses().is_empty()`) only runs when `has_pending` callback is absent; it preserves backward compatibility and current `AddressProvider` trait shape.

If you still want this fallback optimized, we should do it as a separate API-shaping PR (new non-allocating callback/trait method), rather than inside this iOS CI plumbing PR.

**Comment by thepastaclaw** [comment]
Triaged the Swift CI failure for this branch. This is **not flaky** and appears **pre-existing/unrelated to this PR**: the Swift package fails to compile because `DashSDKFFI` headers at the current pinned `rust-dashcore` revision do not expose `FFIDetailedSyncProgress`, `FFINetworks`, and `FFIManagedAccountCollectionSummary` (same deterministic errors across runs 22265218059/22265390864/22265453606/22265820164).\n\nThere is already an open fix PR for this area: https://github.com/dashpay/platform/pull/3107 (`fix(swift-sdk): fix iOS XCFramework build and update Swift SDK for rust-dashcore changes`).\n\nGiven scope rules (avoid patching unrelated pre-existing CI into this PR), I did not add workaround commits here.
